var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "eeeeeeeeeeeeeeexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "               eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeexxxxxxxxxxxxxx",
   "       o                                                          eeeeeeeexxxxxx",
   "  @                          o   o                                        eexxxx",
   "tttttttttth                                                                 eeee",
   "xxxxxxxxxxd      cc       uttttttth                o                            ",
   "xxxxxxxxxxd cc |     |cc uxxxxxxxxxh    |      =       =       utth             ",
   "eeeeeexxxxdwwwwwwwwwwwwwwwbxxxxxxxxxtttttttttttttttttttttttttttxxxxttttth       ",
   "cc    eeexd!!!!!!!!!!!!!!!bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxeeeeeeeeeeexxxd   o   ",
   "cc       eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee           bxxd       ",
   "cc            |                                                      bxxd       ",
   "cc                                                                   bxxd   o   ",
   "cc                           o           o  o         o              bxxd       ",
   "cc                     uth                                            ||        ",
   "cc    o                bxd c  c uth c  =        c    cc                         ",
   "cc                     bxd      bxd ccccccccccccc        cc                 cccc",
   "ccuttttttttth    cc    bxdwwwwwwbxd                                             ",
   "ccbxxxxxxxxxxh       |uxxxttttttxxd                            cc               ",
   "ccbxxxxxxxxxxdwwwwwwwwbxxxxxxxxxxxxttttttttttth                                 ",
   "ccbxxxxxxxxxxd!!!!!!!!bxxxxxxxxxxxxxxxxxxxxxxxxttttttttttttth        uttttthwwww",
   "ttxxxxxxxxxxxd!!!!!!!!bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhwwwwwwuxxxxxxd!!!!",
   "xxxxxxxxxxxxxd!!!!!!!!bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd!!!!!!bxxxxxxd!!!!",
   "xxxxxxxxxxxxxd!!!!!!!!bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdtttttxbxxxxxxd!!!!"],
  ["xxxxxxxxxxxxxxxeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeexxxxxxeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee ",
   "eeeeeeeeeeeeeee                                  bxxxxd    |       |                                              ",
   "        o                         o              bxxxxd                                                           ",
   "     @                                           bxxxxd                                                           ",
   "ttttttth                      utttttttth         bxxxxd                                                           ",
   "xxxxxxxxtttttttttth|  cc  |uttxxxxxxxxxxh=      =bxxxxd                   |                 |          o          ",
   "xxxxxxxxxxxxxxxxxxxwwwwwwwwxxxxxxxxxxxxxd        bxxxxd                   c=               =c                     ",
   "xxxxxxxxxxxxxxxxxxx!!!!!!!!xxxxxxxxxxxxxd        bxxxxd         o     ccccuttttttttttttttttthccc               ccc",
   "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee  =  =  bxxxxd                   bxxxxxxxxxxxxxxxxxd                     ",
   "c                                                bxxxxd       ccccc       bxxxxxxxxxxxxxxxxxd                     ",
   "c                                                bxxxxd                   bxxxxxxxxxxxxxxxxxd                     ",
   "c       o     o                                  bxxxxdccc     o          bxxxxxxxxxxxxxxxxxd                     ",   
   "c                   cc   cc   cc             o   bxxxxd                   bxxxxxxxxxxxxxxxxxd                     ",
   "c     uttttttttttth=       =      cc   cc        eeeeee      ccccc        bxxxxxxxxxxxxxxxxxd                     ",
   "ww    xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwcccccccc                         bxxxxxxxxxxxxxxxxxd                     ",
   "ff    eeeeeeeeeeexx!!!!!!!!!!!!!!!!!!!!!!c                             cccbxxxxxxxxxxxxxxxxxd                     ",
   "ff               xx!!!!!!!!utttttttttttccc                             cccbxxxxxxxxxxxxxxxxxd                     ",
   "ff               xx!!!!!!!!xxxxxxxxxxxd |               utttttttttttttth  bxxxxxxxxxxxxxxxxxd                     ",
   "ff               xxttttttttxxeeeeeeeeee             ccccbxxxxxxxxxxxxxxd  bxxxxxxxxxxxxxxxxxd                     ",
   "ffcc             eeeeeeeeeeee                           bxxxxxxxxxxxxxxd  bxxxxxxxxxxxxxxxxxd                     ",
   "ff                                    o     cccc        bxxxxxxxxxxxxxxd  bxxxxxxxxxxxxxxxxxd                     ",
   "ff   ccc                                                bxxxxxxxxxxxxxxd  bxxxxxxxxxxxxxxxxxd                     ",
   "ff             o                uttttttttttttttth       bxxxxxxxxxxxxxxd  bxxxxxxxxxxxxxxxxxd                     ",
   "ff                              bxxxxxxxxxxxxxxxd       bxxxxxxxxxxxxxxd  bxxxxxxxxxxxxxxxxxd                     ",
   "ff         =  ccc |cc   cc|  cccbxxxxxxxxxxxxxxxd       bxxxxxxxxxxxxxxd  bxxxxxxxxxxxxxxxxxd                     ",
   "ff                              bxxxxxxxxxxxxxxxd       bxxxxxxxxxxxxxxd  bxxxxxxxxxxxxxxxxxd                     ",
   "ffcccc  ccc                     bxxxxxxxxxxxxxxxd       bxxxxxxxxxxxxxxd  bxxxxxxxxxxxxxxxxxd                     ",
   "!!wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbxxxxxxxxxxxxxxdwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxxd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxxd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["d                                                    bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "d                                                    bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "d    @                   o        o                  bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "d                                                    bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "d                          uttttttttttttttth    o    bxxxxxxeeeeeeeeeeeeeeeeeeeeeeexxxxxxxxeeeeeeeeexxxxxxxxxx",
   "d=                    =ccccxxxxxxxxxxxxxxxxd         bxxxxxd                       eeeeeeee         xxxxxxxxxx",
   "d                          eeeeeeeeeeexxxxxd   ccc   bxxxxxd                                        exxxxxxxxx",
   "d                  cc                 bxxxxd         bxxxxxd    o       o                            eeeeeexxx",
   "d                                     bxxxxd         bxxxxxd                                               bxx",
   "d            cccc                     bxxxxd         bxxxxxd                                               bxx",
   "d                                     bxxxxd    o    bxxxxxdcc ccc ccc ccc              cccccc    =        bxx",
   "d  ccccccc                            bxxxxd         bxxxxxd|           |  ccc        ctxxxxxd=            bxx",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbxxxxd   ccc   xxxxxxd    |                   ctxxxxxxxd             bxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxd         eeeeeee        |             ctxxxxxxxxxd  =          bxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd                                    ctxxxxxxxxxxxd             bxx",
   "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeec                                 ctxxxxxxxxxxxxxd    =        bxx",
   "                                      |      cc                   o         ctxxxxxxxxxxxxxxxd             bxx",
   "    ii                                         cccc                       ctxxxxxxxxxxxxxxxxxd      =      bxx",
   "    ii                                           | cccctttttttttttttttttttxxxxxxxxxxxxxxxxxxxd             bxx",
   "    ii        o                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd             bxx",
   "tttttttttttth                                          eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeccccc        bxx",
   "xxxxxxxxxxxxxcc                                                |                |           |              bxx",
   "eeeeeeeeeeeeecccc                                                                                          bxx",
   "                 cccc         o                                                                            bxx",
   "                                                                                                           bxx",
   "wwwwwwwwwwwwwwwwwwwwwwwwutth cccc                                  o                                       bxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!bxxd                                                                   utttttttttttxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!bxxd      ccc       =       ccc           ccc=              ccc        bxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!bxxd           ccccccc                                                 bxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!bxxd                               ccc            ccc                  bxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!bxxd                                                                   bxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!bxxd                                                                   bxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxd                                                                   bxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxd                                                                   bxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxd          |          |             |                |           |  bxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxdwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwbxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!bxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;